### PR TITLE
Updates for issues

### PR DESCRIPTION
**Pull request by CodeHermez**
## Pull Request

**Description:**

updates for issues made after sprint review and updates to the system

[Provide a concise summary of your changes and why they are necessary.]

**Related Issues:**

[Reference any related issues or documents.]

**Type of Change:**

- [x] Bug Fix
- [ ] New Feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Documentation Update

**Checklist:**

- [ ] My code follows the coding standards of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have added/updated relevant documentation.
- [ ] My changes generate no new warnings or errors.
- [ ] I have tested my changes.

**Screenshots (if applicable):**

[Add screenshots to help reviewers understand the changes visually.]

**Reviewers:**

- @reviewer1
- @reviewer2

**Additional Notes:**

[Any additional information that may be helpful for reviewers.]

### CODE REVIEW

**Review by KumbiraiShonhiwa — APPROVED** [review]

**Comment by JessBloem** [comment]
I see you made changes to client files in api-gateway. Please confirm with @Hamza-Mokiwa that these changes are okay

**Comment by Hamza-Mokiwa** [comment]
Yes, I asked him to make those changes, its all good

**Comment by KumbiraiShonhiwa** [comment]
please pull from dev

**Review by JessBloem — APPROVED** [review]
All good👌

**Pull request merged**
