### PR TITLE
Feature/job improvement v2

### PR DESCRIPTION
**Pull request by Hamza-Mokiwa**
## Pull Request

**Description:**

- Adds fine-grained endpoints for assigning employees and teams to jobs
- Adds foundation for RBA in all Endpoints by adding EmployeeIds to various Dtos
- Small bug fixes in Client

**Related Issues:**

[Reference any related issues or documents.]

**Type of Change:**

- [X] Bug Fix
- [X] New Feature
- [X] Enhancement
- [X] Refactoring
- [ ] Documentation Update

**Checklist:**

- [X] My code follows the coding standards of this project.
- [X] I have performed a self-review of my code.
- [X] I have added/updated relevant documentation.
- [X] My changes generate no new warnings or errors.
- [X] I have tested my changes.

**Reviewers:**

- @JessBloem

### CODE REVIEW

**Review by JessBloem — COMMENTED** [review]
Does not run on my local envioment. 
[Nest] 36357  - 07/29/2024, 7:25:35 AM   ERROR [ExceptionHandler] "undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at new FcmNotificationService (/home/jessica/University/WorkWise-Central/src/api-gateway/src/notification/fcm-notification.service.ts:7:33)
    at Injector.instantiateClass (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/injector.js:65:45)
    at Injector.resolveConstructorParams (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/injector.js:144:24)
    at Injector.loadInstance (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/injector.js:70:13)
    at Injector.loadProvider (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/injector.js:97:9)
    at /home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 9)
    at InstanceLoader.createInstancesOfProviders (/home/jessica/University/WorkWise-Central/src/api-gateway/node_modules/@nestjs/core/injector/instance-loader.js:55:9)

**Comment by Hamza-Mokiwa** [comment]
@JessBloem  You need the new .env variable

**Comment by Hamza-Mokiwa** [comment]
I will share it soon, on discord

**Review by JessBloem — APPROVED** [review]
Looks good now🤠

**Pull request merged**
